#!/bin/bash
#
#PBS -N 2X-200-500_njst_fasttree_genetrees
#PBS -l nodes=1:ppn=1
#PBS -l cput=4:00:00
#PBS -l walltime=4:00:00
#PBS -t 1-20
#

for N in 10 25 50 100 200; do 
    for K in 50 100 200; do
	~/phylogenetic_tools/njst-package/njst ~/scratch/2X-200-500/R${PBS_ARRAYID}/relabeled_shortened_data_${N}_subset_${K}/all_fasttree.genetrees ~/AGBsvdquartets/2X-200-500/R${PBS_ARRAYID}/njst_fasttree_genetrees_${N}_sites_${K}_genes.tree
    done
done