#!/bin/bash
#
#PBS -N 2X-200-500_astral_fasttree_genetrees
#PBS -l nodes=1:ppn=1
#PBS -l cput=4:00:00
#PBS -l walltime=3:00:00
#PBS -t 1-20
#

FOLDERPATH=~/scratch/2X-200-500/R${PBS_ARRAYID}
for N in 10 25 50 100 200; do 
    for K in 50 100 200; do
	cd ${FOLDERPATH}/relabeled_shortened_data_${N}_subset_${K}/
	cat *_fasttree_genetree >> all_fasttree.genetrees
	java -jar ~/phylogenetic_tools/4.7.6.astral/astral.4.7.6.jar -i all_fasttree.genetrees -o ~/AGBsvdquartets/2X-200-500/R${PBS_ARRAYID}/astral_fasttree_genetrees_${N}_sites_${K}_genes.tree
    done
done