#Qsub script to run unpartitioned concatenation with FastTree-2 or RAxML on 15-taxon datasets
#Usage: qsub get_unpartitioned_concatenation_15-taxon_allsites.pbs

#!/bin/bash                  
#                                                           
#PBS -N 15-taxon_concat_raxml_10runs
#PBS -l nodes=1:ppn=1
#PBS -l cput=4:00:00
#PBS -l walltime=4:00:00
#PBS -t 1-10
#  

#Run unpartitioned concatenation with FastTree-2
#for N in 10 25 50 100 200; do
#    for K in 100 500 1000; do
#	~/AGBsvdquartets/FastTreeMP -gtr -nt -gamma ~/scratch/15-taxon_redo/${PBS_ARRAYID}/relabeled_shortened_combined_${N}_subset_${K}.phy > /projects/tallis/jed/AGBsvdquartets/15-taxon_redo/${PBS_ARRAYID}/concatenation_fasttree_${N}_sites_${K}_genes.tree
#done
#done

#RUn unpartitioned concatenation with RAxML
for N in 10 25 50 100 200; do
    for K in 100 500 1000; do
	~/phylogenetic_tools/standard-RAxML/raxmlHPC-SSE3 -m GTRGAMMA -s ~/scratch/15-taxon_redo/${PBS_ARRAYID}/relabeled_shortened_combined_${N}_subset_${K}.phy -w /projects/tallis/jed/AGBsvdquartets/15-taxon_redo/${PBS_ARRAYID} -n concatenation_raxml_10runs_${N}_sites_${K}_genes.tree -N 10 -p $RANDOM
done
done
