#Qsub script to run unpartitioned concatenation with RAxML on the 37-taxon 2X mammalian simulated dataset
#Usage: qsub get_unpartitioned_concatenation_2X-200-500.pbs

#!/bin/bash                  
#                                                           
#PBS -N 2X-200-500_concat_raxml_10runs
#PBS -l nodes=1:ppn=1
#PBS -l cput=4:00:00
#PBS -l walltime=4:00:00
#PBS -t 1-20
#  

for N in 10 25 50 100 200; do
    for K in 50 100 200; do
	~/phylogenetic_tools/standard-RAxML/raxmlHPC-SSE3 -m GTRGAMMA -s ~/scratch/2X-200-500/R${PBS_ARRAYID}/relabeled_shortened_combined_${N}_subset_${K}.phy -w /projects/tallis/jed/AGBsvdquartets/2X-200-500/R${PBS_ARRAYID} -n concatenation_raxml_10runs_${N}_sites_${K}_genes.tree -N 10 -p $RANDOM
done
done
