#!/bin/bash
#                                                           
#PBS -N 11-taxon_20_qmc
#PBS -l nodes=1:ppn=1
#PBS -l cput=2:00:00
#PBS -l walltime=2:00:00
#PBS -t 1-50
#  
MODEL=model.10.200000.0.000001000

for N in 10 25 50 100 200; do
    for K in 100 500 1000; do
        ~/AGBsvdquartets/data_processing_redo/getquartets_run_svdquartets_qmc.sh 11-taxon_redo/${MODEL}/${PBS_ARRAYID} ~/scratch ${N} ${K} A
    done
done
