#!/bin/bash
#
#PBS -N 2X-200-500_convert_nexus_to_phy
#PBS -l nodes=1:ppn=1
#PBS -l cput=4:00:00
#PBS -l walltime=4:00:00
#

for SPECIESNUMBER in {1..20}; do
    for N in 10 25 50 100 200; do
	for K in 50 100 200; do
	    python ~/phylogenetic_tools/bioscripts.convert-0.4/bioscripts/convert/convalign.py phylip ~/scratch/2X-200-500/R${SPECIESNUMBER}/relabeled_shortened_combined_${N}_subset_${K}.nex 
	done
    done
done
